import { test, expect } from '@playwright/test';

test('shipment to forecast-backed charter decision, constraints, history and narrow screen', async ({page,request}) => {
  test.setTimeout(240000);
  const errors: string[]=[];
  page.on('pageerror',e=>errors.push(e.message));
  const preparation=await request.post('/api/charter/demos/prepare',{data:{},timeout:180000});
  expect(preparation.ok()).toBeTruthy();
  await page.goto('/');
  await page.getByRole('button',{name:'06 Charter decision'}).click();
  await page.getByRole('button',{name:'A · WAIT OPPORTUNITY'}).click();
  await expect(page.getByTestId('charter-recommendation')).toHaveText('WAIT');
  await expect(page.getByTestId('charter-cost-chart')).toBeVisible();
  await expect(page.locator('.recharts-area')).toHaveCount(1);
  await expect(page.getByText('Inputs changed;',{exact:false})).toHaveCount(0);
  const response=await request.post('/api/charter/analyze',{data:(await preparation.json())[0].request});
  const decision=await response.json();
  expect(decision.voyage_context.feasibility.status).not.toBe('FAIL');
  expect(decision.forecast_metadata.model_version).toBe('freight-v1.1');
  expect(decision.forecast_metadata.target.provenance.source_type).toBe('SIMULATED');
  expect(decision.market_snapshot.congestion_used[1].basis).toBe('MARKET_OBSERVATION');
  const chosen=decision.candidate_decisions.find((c:{decision_status:string})=>c.decision_status==='RECOMMENDED');
  expect(chosen.savings_vs_now.p50).toBeCloseTo(decision.current_charter_cost-chosen.costs.p50.total_logistics_cost,2);
  expect(chosen.buffered_arrival<=decision.request.shipment.required_arrival_date).toBeTruthy();
  expect(chosen.costs.p50.ocean_freight).toBeCloseTo(chosen.hire_usd_per_day.p50*decision.assumptions.hire_days,2);
  expect(decision.performance.forecast_training_calls).toBe(0);
  await page.screenshot({path:'test-results/charter-wait.png',fullPage:true});
  await page.getByRole('button',{name:'B · TIGHT DEADLINE'}).click();
  await expect(page.getByTestId('charter-recommendation')).toHaveText('LOCK NOW');
  await expect(page.getByText('14 later dates excluded:',{exact:false})).toBeVisible();
  // Deadline and buffer edits recalculate without another Analyze click.
  await page.getByLabel('Required arrival',{exact:true}).fill('2026-10-20');
  await expect(page.getByTestId('charter-recommendation')).toHaveText('WAIT');
  await page.getByLabel('Schedule buffer · days',{exact:true}).fill('30');
  await expect(page.getByTestId('charter-recommendation')).toHaveText('NO SAFE WAIT WINDOW');
  await page.getByRole('button',{name:'C · HIGH UNCERTAINTY'}).click();
  await expect(page.getByTestId('charter-recommendation')).toHaveText('LOCK NOW');
  await expect(page.getByText('HIGH UNCERTAINTY POLICY',{exact:false}).first()).toBeVisible();
  await page.getByRole('button',{name:'D · INSUFFICIENT DATA'}).click();
  await expect(page.getByTestId('charter-recommendation')).toHaveText('INSUFFICIENT DATA');
  await page.getByRole('button',{name:'A · WAIT OPPORTUNITY'}).click();
  await expect(page.getByTestId('charter-recommendation')).toHaveText('WAIT');
  await page.getByLabel('Destination port',{exact:true}).selectOption('Haldia');
  await expect(page.getByTestId('charter-recommendation')).toHaveText('NO SAFE WAIT WINDOW');
  await page.getByRole('button',{name:'09 Decision history'}).click();
  await expect(page.getByRole('heading',{name:'Saved charter decisions'})).toBeVisible();
  await page.getByRole('button',{name:'Open evidence'}).first().click();
  await expect(page.getByTestId('charter-recommendation')).toBeVisible();
  await page.setViewportSize({width:390,height:844});
  await expect(page.getByRole('heading',{name:'Shipment & procurement preferences'})).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1)).toBeTruthy();
  await page.screenshot({path:'test-results/charter-mobile.png',fullPage:true});
  expect(errors).toEqual([]);
});
